### ISSUE TITLE
Text not wrapping

### ISSUE THREAD

**Issue by andreivettor** [jagnani73/react-easy-marquee#24]
**Describe the bug**
white-space: nowrap on inner <span> doesn't allow marquee item text to wrap and makes the <span> extend beyond parent container.

**To Reproduce**
1. Have text wider than marquee container
2. Observe wrapping issues

**Expected behavior**
The text should wrap and stay inside the parent container

**Screenshots**
<img width="585" alt="image" src="https://user-images.githubusercontent.com/32334900/154084401-a24af262-7c5e-4d3f-94bd-b4f862aeefcd.png">

**Aditional information**
This is for a vertical marquee

**Comment by jagnani73** [comment]
Hey @andreivettor 
To wrap text in the marquee, you need to place the text in another parent component, let's say maybe a `div`, and add a `white-space` property to that `div` (maybe with a fixed `width` or a `max-width). I kept it `nowrap` for the direct children of the Marquee, however, you control the grandchildren of the marquee.

I hope  this helps!

**Comment by andreivettor** [comment]
Thanks @jagnani73! Much cleaner this way. But still, shouldn't wrapping be default behavior? At least, I expect it when using components like this.

**Comment by jagnani73** [comment]
Its shouldn't actually, for the use case:
`<Marquee>What will happen to this text in this use case?</ Marquee>`
Keeping the `white-space: nowrap` still enables the flexibility to do everything desired, however, keeping `white-space: wrap` will eradicate that freedom.

**Comment by andreivettor** [comment]
@jagnani73 I see what you mean. Maybe a specific style could be implemented for axis={"Y"}? That's the use case I am concerned about.

**Comment by jagnani73** [comment]
There's no need since the `grandchild` logic works 😄

**Comment by jagnani73** [comment]
> 

@andreivettor There's no need to that since the `grandchild` logic works 😄

**Comment by andreivettor** [comment]
@jagnani73 I'm not sure what you mean by that. Then maybe you can specify in the docs that on the Y axis wrapping needs to be set specifically with white-space: normal?

**Comment by jagnani73** [comment]
> @jagnani73 I'm not sure what you mean by that. Then maybe you can specify in the docs that on the Y axis wrapping needs to be set specifically with white-space: normal?

Ill figure something out!
Thank you!
