### ISSUE TITLE
Rendering warnings

### ISSUE THREAD

**Issue by andreivettor** [jagnani73/react-easy-marquee#25]
**Describe the bug**
Warnings when initially rendering the component. Not technically a bug but ideally avoided.

**To Reproduce**
1. Render marquee

**Expected behavior**
No warnings

**Screenshots**
<img width="580" alt="image" src="https://user-images.githubusercontent.com/32334900/154086375-35bd6b41-053e-4fa0-94e2-860e0dd1fbfa.png">

**Additional context**

**Comment by LwcReber** [comment]
@jagnani73  Hi, the 1.2.3  still has this warnings😭

**Comment by jagnani73** [comment]
Hey @LwcReber 
Can you please attach some screenshots for support?
