### ISSUE TITLE
marquee reverse doesn't work on Safari

### ISSUE THREAD

**Issue by Kcin1993** [jagnani73/react-easy-marquee#28]
**Describe the bug**
When 

**To Reproduce**
1. Open the Safari browser
2. Go to the demo site https://jagnani73.github.io/react-easy-marquee/ and open the reverse option.

**Expected behavior**
On Safari browser
1. When the reverse option is false the direction is left to right.
2. When the reverse option is true the direction is right to left.

**Screenshots**
https://user-images.githubusercontent.com/8435927/162687004-6a24e8c7-3d82-486f-adad-58eaa208472d.mov

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser Safari 
 - Version 15.2（17612.3.6.1.6）

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: ios 15.4.1
 - Browser Safari
 - Version Same as ios version

**Comment by jagnani73** [comment]
Hey @Kcin1993 !
Thank you reporting this issue, feel free to work on it if you want tp; meanwhile I will try to look for a solution as well

**Comment by jagnani73** [comment]
Fixed in #29
