### ISSUE TITLE
Bug: Demo link is broken

### ISSUE THREAD

**Issue by ruddha2001** [jagnani73/react-easy-marquee#8]
**Describe the bug**
The demo link (https://github.com/jagnani73/github.io/reacy-easy-marqueee) in the Readme returns a 404.

**To Reproduce**
1.Click on 'Demo' in the readme
2. 404 Page is encountered

**Expected behavior**
A working demo should be appearing.

**Screenshots**
![image](https://user-images.githubusercontent.com/48330897/122032856-a559c880-cded-11eb-965f-dcebf5d83238.png)

**Comment by jagnani73** [comment]
Fixed in 01a4965fafc7df64951a2abb0c35971b713e1acd
